### ISSUE TITLE
Latest release notes / Project visibility

### ISSUE THREAD

**Issue by fabricat** [jenkinsci/build-monitor-plugin#635] opened 2022-10-10 14:39 UTC
Hello,
I have been asked to evaluate and install this Jenkins plugin, but I cannot find release notes for the latest version 1.13.
The [Jenkins plugins directory entry](https://plugins.jenkins.io/build-monitor-plugin/) does not provide any issue tracker, and I could only find an indirect link to this GH repo in the Documentation text.

Please, can you enrich the plugin metadata, and add a changelog for newer versions?
IMHO it should require a little effort, but will provide greater visibility to the plugin development health status 😉

**Comment by alecharp** [comment] 2022-10-27 13:53
> I could only find an indirect link to this GH repo in the Documentation text.

The problem is that the update-center generation code is expecting the plugin source-code to be hosted in the `jenkinsci` organization in GitHub. This is described here: https://www.jenkins.io/doc/developer/publishing/requesting-hosting/#open-hosting-request. However, this plugin was not transferred to that organization. 

In the update-center code (https://github.com/jenkins-infra/update-center2/blob/7d77cd45525fe5f9ddbc9ec11b1968c00952a2fa/src/main/java/io/jenkins/update_center/HPI.java#L461), the repository of the plugin is excluded. 

The issue tracker problem is because none is documented in https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-build-monitor-plugin.yml.

> add a changelog for newer versions?

The repository is not using `release-drafter` nor any manual release note file.

@jan-molak would it be ok to transfer the plugin to the `jenkinsci` organization? The plugin could benefit from dependabot, jep-229, release-drafter, better integration with plugins.jenkins.io..

**Comment by jan-molak** [comment] 2022-10-27 14:04
@alecharp - last time I've spoken with CloudBees regarding transfer there were some challenges that prevented the transfer; happy to get back to this conversation over email though

**Comment by alecharp** [comment] 2022-10-27 14:08
> last time I've spoken with CloudBees

To be specific, this hosting process has nothing to do with CloudBees but with the Jenkins project. 
I was here speaking as a Jenkins community member and because I'm working on https://github.com/jenkins-infra/plugin-health-scoring/ which shows that the plugins is not hosted _correctly_.

**Comment by jan-molak** [comment] 2022-10-27 14:14
Right, thanks for the context. There are several contributors from CloudBees helping out with Jenkins Build Monitor at the moment, so if there are PRs you'd like to propose to improve integration with Jenkins ecosystem we'll be happy to review them?

**Comment by alecharp** [comment] 2022-10-27 14:17
> if there are PRs you'd like to propose to improve integration with Jenkins ecosystem

the transfer of the repository cannot be done with a pull request. For the release-drafter, cd etc., there configurations are _easier_ once in the jenkinsci organization as they can simply extend basic configuration from https://github.com/jenkinsci/.github

**Comment by jan-molak** [comment] 2022-10-31 10:56
Thanks for the explanation, I'll reach out to CloudBees and the Jenkins project to see what's changed since we last discussed this some (long) time ago #418

**Comment by alecharp** [comment] 2022-10-31 11:05
> I'll reach out to CloudBees

I'm not sure why you need to reach out. If so, I can help you, as employee of CloudBees.
For the Jenkins Project, I can also help, as a long time contributor and I'm not also part of the hosting process. 

From https://github.com/jan-molak/jenkins-build-monitor-plugin/issues/418, I don't know what you need for your end-to-end tests. For the release process, it's still up to you to use the decide to use semantic versioning or not, but that was also the case back then.

**Comment by basil** [comment] 2022-10-31 14:59
To be clear, this issue would not exist if this repository followed the standard conventions for the Jenkins project:

- Repository hosted in the `jenkinsci` GitHub organization
- CI build done on https://ci.jenkins.io
- CD done with [JEP-229](https://github.com/jenkinsci/jep/blob/adcc3f20dbaa8166fe9d2aec1ea8981eb51614f2/jep/229/README.adoc)

> if there are PRs you'd like to propose to improve integration with Jenkins ecosystem we'll be happy to incorporate them?

We will not be proposing PRs to improve integration with the Jenkins ecosystem for repositories not hosted in the `jenkinsci` GitHub organization, using GitHub Actions for CI, and using something other than JEP-229 for CD.

If you would like to transfer this repository to the `jenkinsci` GitHub organization, we will be happy to help move the CI to https://ci.jenkins.io and the CD to JEP-229, which will resolve issues like this.

**Comment by jan-molak** [comment] 2022-10-31 17:08
@alecharp @basil - I appreciate your offering to help and support Jenkins Build Monitor. I'll reach out to people I've spoken with originally to discuss the details of any transfers.

**Comment by basil** [comment] 2022-10-31 17:53
Thanks @jan-molak. To transfer the repository from the `jan-molak` GitHub organization to the `jenkinsci` GitHub organization, you can file a ticket at https://github.com/jenkins-infra/helpdesk.

**Comment by jan-molak** [comment] 2022-10-31 18:09
Thanks @basil I'm on holiday at the moment with limited access to the Internet. I'll look into it when I'm back home next week. Thanks for all the details!

**Comment by andham** [comment] 2022-12-20 13:27
Any update on this? As @fabricat I was also looking into this plugin to evaluate it and found the info lacking. It makes the process a bit more difficult and the plugin also looks less attractive (it doesn't look maintained).

**Comment by basil** [comment] 2022-12-20 15:36
From the Jenkins project's perspective, we are still happy to help normalize this plugin's hosting and release process. The only step that is necessary to begin the process is for Jan Molak to transfer the plugin to the `jenkinsci` GitHub organization.

**Comment by basil** [comment] 2023-03-09 02:28
[Build Monitor View](https://plugins.jenkins.io/build-monitor-plugin/) is now [hosted in the jenkinsci GitHub organization](https://github.com/jenkinsci/build-monitor-plugin), [built on ci.jenkins.io](https://ci.jenkins.io/job/Plugins/job/build-monitor-plugin/job/master/), and deployed with our standard CD process (including changelogs generated with Release Drafter).

**Closed by basil** 2023-03-09 02:29 UTC
